### ISSUE TITLE
After installing, TeaSpeak does not launch at all

### ISSUE THREAD

**Issue by redstonedesigner** [TeaSpeak/TeaClient#37]
I'm on Windows 10 Professional, and I cannot get the application to launch.

I have tried to install and launch the following versions, all with the same result:

- 1.4.9
- 1.4.8
- 1.4.7
- 1.4.6
- 1.1.0

Nothing is showing and I do not get to a splashscreen of any kind.

**Comment by WolverinDEV** [comment]
Hey,
what happens when you're trying to opening the client via the cmd?

**Comment by redstonedesigner** [comment]
What command is that?

EDIT: Sorry, I didn't understand.  Here is the output:

```
Native module path: d:\Program Files\TeaSpeak\Client\resources\natives                        Versions:                                                                                       TeaSpeak Client: 1.4.9                                                                        node: 12.13.0                                                                                 v8: 8.0.426.16-electron.0                                                                     uv: 1.32.0                                                                                    zlib: 1.2.11                                                                                  brotli: 1.0.7                                                                                 ares: 1.15.0                                                                                  modules: 76                                                                                   nghttp2: 1.39.2                                                                               napi: 5                                                                                       llhttp: 1.1.4                                                                                 http_parser: 2.8.0                                                                            openssl: 1.1.0                                                                                icu: 65.1                                                                                     unicode: 12.1                                                                                 electron: 8.0.0                                                                               chrome: 80.0.3987.86                                                                        Parsed CMD arguments [ 'd:\\Program Files\\TeaSpeak\\Client\\TeaClient.exe', [length]: 1 ] as {                                                                                               _: [ [length]: 0 ],                                                                           '--': [ [length]: 0 ],                                                                        has_flag: [Function] { [length]: 0, [name]: '' },                                             value: [Function] { [length]: 0, [name]: '' },                                                has_value: [Function] { [length]: 0, [name]: '' }                                           }                                                                                             Main app executed!                                                                            Parsed CMD arguments [ 'd:\\Program Files\\TeaSpeak\\Client\\TeaClient.exe', [length]: 1 ] as {                                                                                               _: [ [length]: 0 ],                                                                           '--': [ [length]: 0 ],                                                                        has_flag: [Function] { [length]: 0, [name]: '' },                                             value: [Function] { [length]: 0, [name]: '' },                                                has_value: [Function] { [length]: 0, [name]: '' }                                           }                                                                                             Setting up render backend                                                                     Spawn loading screen                                                                          Open UI loader window.                                                                        (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397                                                    request: http://clientapi.teaspeak.de//api.php?type=update-info                               Uncaught Exception thrown:                                                                    SyntaxError: Unexpected token < in JSON at position 0                                             at JSON.parse (<anonymous>)                                                                   at Request._callback (d:\Program Files\TeaSpeak\Client\resources\app.asar\modules\core\app-updater\index.js:61:35)                                                                          at Request.self.callback (d:\Program Files\TeaSpeak\Client\resources\app.asar\node_modules\request\request.js:185:22)                                                                       at Request.emit (events.js:210:5)                                                             at Request.<anonymous> (d:\Program Files\TeaSpeak\Client\resources\app.asar\node_modules\request\request.js:1154:10)                                                                        at Request.emit (events.js:210:5)                                                             at IncomingMessage.<anonymous> (d:\Program Files\TeaSpeak\Client\resources\app.asar\node_modules\request\request.js:1076:12)                                                                at Object.onceWrapper (events.js:299:28)                                                      at IncomingMessage.emit (events.js:215:7)                                                     at endReadableNT (_stream_readable.js:1183:12)                                            Shutting down app.                                                                            App has been finalized.
```

**Comment by WolverinDEV** [comment]
Is your PC able to connect top the internet?
Ofc this should not happen, but I assume that somehow the client fetches some data (json to be precise).
For some reason the fetched data seems to be invalid (`Unexpected token < in JSON at position 0`).
Seems like the client actually retrieves something starting with `<` which reminds me of `<html ...` which can be some kind of error page.

**Comment by redstonedesigner** [comment]
My computer is perfectly capable of connecting to the internet.  If it were not, how would I be able to send this message?

**Comment by redstonedesigner** [comment]
Found the issue.

My network administrator seems to decide that running network security software that was shut down for over a year was a good idea....
Uninstalled that software and everything worked fine.

In case you were wondering, it was BlueCoat K9 Web Protection and it has some of your sites categorized as Spyware / Malware Sources.
